$NetBSD: patch-config_elasticsearch.yml,v 1.4 2015/11/12 15:37:08 fhajny Exp $

Define various paths

--- config/elasticsearch.yml.orig	2015-10-21 08:41:12.000000000 +0000
+++ config/elasticsearch.yml
@@ -31,10 +31,16 @@
 # Path to directory where to store the data (separate multiple locations by comma):
 #
 # path.data: /path/to/data
+path.data: @ES_DBDIR@
 #
 # Path to log files:
 #
 # path.logs: /path/to/logs
+path.logs: @ES_LOGDIR@
+
+path.conf: @PKG_SYSCONFDIR@
+path.plugins: @ES_LIBDIR@/plugins
+path.work: @ES_TMPDIR@
 #
 # ----------------------------------- Memory -----------------------------------
 #
