# $NetBSD$

PKGNAME=	indexinfo-0.2.6
CATEGORIES=	print
MASTER_SITES=	https://github.com/bapt/indexinfo/archive/
DIST_SUBDIR=	indexinfo
DISTFILES=	0.2.6.tar.gz

MAINTAINER=	draco@marino.st
HOMEPAGE=	https://github.com/bapt/indexinfo
COMMENT=	Utility to regenerate the GNU info page index

pre-install:
	${MKDIR} ${DESTDIR}${PREFIX}/bin

.include "../../mk/bsd.pkg.mk"
