@@ -1,23 +1,16 @@
 # $NetBSD: Makefile,v 1.4 2016/08/27 21:57:05 khorben Exp $
 
-VERSION=	1.8.7
-DISTNAME=	${VERSION}
-PKGNAME=	pkg-${VERSION}
+DISTNAME=	pkg-1.8.7
 CATEGORIES=	pkgtools
-MASTER_SITES=	${MASTER_SITE_GITHUB:=freebsd/pkg/archive/}
+MASTER_SITES=	http://files.etoilebsd.net/pkg/
+EXTRACT_SUFX=	.tar.xz
 
 MAINTAINER=	khorben@defora.org
 HOMEPAGE=	https://wiki.freebsd.org/pkgng
 COMMENT=	Package management tool for FreeBSD
 LICENSE=	2-clause-bsd
 
-WRKSRC=		${WRKDIR}/pkg-${VERSION}
-
 GNU_CONFIGURE=	yes
-USE_LIBTOOL=	yes
-USE_TOOLS+=	autoconf
-USE_TOOLS+=	automake
-USE_TOOLS+=	pkg-config
 USE_LANGUAGES=	c c++
 
 CPPFLAGS+=	-D_LOCALBASE="\"${PREFIX}\""
@@ -57,8 +50,9 @@
 SUBST_SED.pkgconf-prefix+=	-e "s|/usr/local|${PREFIX}|g"
 SUBST_MESSAGE.pkgconf-prefix=	Correct the installation prefix in pkg.conf(5).
 
-pre-configure:
-	cd ${WRKSRC} && ./autogen.sh
+post-patch:
+	${CP} ${FILESDIR}/readpassphrase_compat.h \
+		${WRKSRC}/src/
 
 post-install:
 	${MV} ${DESTDIR}${PREFIX}/etc/bash_completion.d/_pkg.bash \
